# -*- coding: utf-8 -*-
"""TelecomX_BR.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/11xb1RzMsijItvwbcRmw0LoV2ioiNKRKu

#📌 Extracão
"""

import pandas as pd
import requests
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

"""### Leitura do Json"""

url = "https://raw.githubusercontent.com/ingridcristh/challenge2-data-science/refs/heads/main/TelecomX_Data.json"
df = pd.read_json(url)
df

"""### Normalizar oos dados aninhados"""

df_customer = pd.json_normalize(df['customer'])
df_phone = pd.json_normalize(df['phone'])
df_internet = pd.json_normalize(df['internet'])
df_account = pd.json_normalize(df['account'])
df_final = pd.concat([df[['customerID','Churn']],df_customer, df_phone, df_internet, df_account], axis=1)
df_final

"""#🔧 Transformação

###Limpeza dos dados
"""

df_final['Contract'] = df_final['Contract'].str.replace('-', '', regex=True)
df_final['PaymentMethod'] = df_final['PaymentMethod'].str.replace('(automatic)', '', regex=True)
df_final['PaymentMethod'] = df_final['PaymentMethod'].str.replace('[()]', '', regex=True)
df_final['Charges.Total'] = df_final['Charges.Total'].apply(
    lambda x: float(str(x).replace(' ', '')) if str(x).strip() != '' else 0.0
)
df_final

# Remover valores nulos do Churn
# Identifica o valor que está causando o problema
valores_a_remover = df_final[~df_final['Churn'].isin(['Yes', 'No'])]['Churn'].unique()

# Filtra o DataFrame para manter apenas as linhas com 'Yes' ou 'No'
df_final = df_final[df_final['Churn'].isin(['Yes', 'No'])].copy()
print(df_final['Churn'].value_counts())

num_duplicados = df_final.duplicated().sum
print(f"\n Registros duplicados no dataset: {num_duplicados}")

print("\n Informações gerais:")
df_final.info()

print("\n Valores únicos por coluna:")
for i in df_final.columns:
    print(f"{i}: {df_final[i].nunique()} valores únicos")

print("\n Valores ausentes por coluna:")
df_final.isnull().sum()

"""#📊 Carga e análise"""

print("Análise Descritiva \n")
df_final.describe()

df_final['Churn'].value_counts()

# Contagem de clientes que não tiveram churn ('No') e não usam OnlineSecurity ('No')
count = df_final[(df_final['Churn'] == 'No') & (df_final['OnlineSecurity'] == True)].shape[0]

print(f"Número de clientes com Churn 'No' e OnlineSecurity 'No': {count}")

sns.set_style("whitegrid")
plt.figure(figsize=(8, 6))
sns.countplot(data=df_final, x='Churn', palette='viridis')

plt.title('Distribuição de evasão de clientes (Churn)', fontsize=16)
plt.xlabel('Churn', fontsize=12)
plt.ylabel('Número de Clientes', fontsize=12)

for p in plt.gca().patches:
    plt.gca().annotate(f'{int(p.get_height())}',
                       (p.get_x() + p.get_width() / 2., p.get_height()),
                       ha='center', va='center',
                       xytext=(0, 10),
                       textcoords='offset points')

plt.show()

sns.set_style("whitegrid")
plt.figure(figsize=(8, 6))
sns.countplot(data=df_final, x='gender', hue='Churn', palette='viridis')

plt.title('Distribuição de evasão por Gênero', fontsize=16)
plt.xlabel('Gênero', fontsize=12)
plt.ylabel('Número de Clientes', fontsize=12)
plt.legend(title='Churn', loc='upper right')

ax = plt.gca()
for p in ax.patches:
    height = p.get_height()
    if height > 0:  # Verifica se a altura da barra é maior que zero
        ax.annotate(f'{int(height)}',
                    (p.get_x() + p.get_width() / 2., height),
                    ha='center', va='center',
                    xytext=(0, 10),
                    textcoords='offset points')

plt.show()

plt.figure(figsize=(10, 6))
sns.countplot(data=df_final, x='Contract', hue='Churn', palette='viridis')

plt.title('Distribuição de Churn por Tipo de Contrato', fontsize=16)
plt.xlabel('Tipo de Contrato', fontsize=12)
plt.ylabel('Número de Clientes', fontsize=12)
plt.legend(title='Churn', loc='upper right')

ax = plt.gca()
for p in ax.patches:
    height = p.get_height()
    if height > 0:
        ax.annotate(f'{int(height)}',
                    (p.get_x() + p.get_width() / 2., height),
                    ha='center', va='center',
                    xytext=(0, 10),
                    textcoords='offset points')

plt.show()

plt.figure(figsize=(12, 7))
sns.countplot(data=df_final, x='PaymentMethod', hue='Churn', palette='viridis')

plt.title('Distribuição de Churn por Método de Pagamento', fontsize=16)
plt.xlabel('Método de Pagamento', fontsize=12)
plt.ylabel('Número de Clientes', fontsize=12)
plt.xticks(rotation=15, ha='right')
plt.legend(title='Churn', loc='upper right')

ax = plt.gca()
for p in ax.patches:
    height = p.get_height()
    if height > 0:
        ax.annotate(f'{int(height)}',
                    (p.get_x() + p.get_width() / 2., height),
                    ha='center', va='center',
                    xytext=(0, 10),
                    textcoords='offset points')

plt.show()

sns.set_style("whitegrid")
plt.figure(figsize=(8, 6))
ax = sns.countplot(data=df_final, x='SeniorCitizen', hue='Churn', palette='viridis')

for p in ax.patches:
    height = p.get_height()
    if height > 0:
        ax.annotate(f'{int(height)}',
                    (p.get_x() + p.get_width() / 2., height),
                    ha='center', va='center',
                    xytext=(0, 10),
                    textcoords='offset points')

plt.title('Distribuição de Churn por Senioridade', fontsize=16)
plt.xlabel('Senior Citizen', fontsize=12)
plt.ylabel('Número de Clientes', fontsize=12)
plt.legend(title='Churn', loc='upper right')

plt.show()

sns.set_style("whitegrid")
fig, axes = plt.subplots(1, 3, figsize=(18, 6)) # 1 linha, 3 colunas

numeric_vars = ['tenure', 'Charges.Monthly', 'Charges.Total']
titles = ['Média de Tempo de Contrato', 'Média de Gastos Mensais', 'Média de Total Gasto']
y_labels = ['Tempo de Contrato (Meses)', 'Gastos Mensais', 'Total Gasto']

for i, var in enumerate(numeric_vars):
    sns.barplot(ax=axes[i], data=df_final, x='Churn', y=var, palette='viridis')

    axes[i].set_title(titles[i], fontsize=14)
    axes[i].set_xlabel('Churn')
    axes[i].set_ylabel(y_labels[i])

    for p in axes[i].patches:
        height = p.get_height()
        axes[i].annotate(f'{height:.2f}',
                         (p.get_x() + p.get_width() / 2., height),
                         ha='center', va='bottom',
                         xytext=(0, 5),
                         textcoords='offset points')

plt.tight_layout()
plt.show()

"""#📄Relatorio Final

---

### 📄 Análise de Evasão de Clientes (Churn)

Este relatório apresenta uma análise sobre a evasão de clientes (Churn) da empresa TelecomX, focando em entender os principais motivos que levam os clientes a cancelar seus serviços.

---

#### 🔍 **O que foi feito?**

Neste projeto, realizamos as seguintes etapas para analisar o problema de Churn:

1.  **Extração e Limpeza de Dados:** Importamos os dados de um arquivo JSON, organizamos as informações e realizamos uma limpeza rigorosa, tratando valores ausentes e corrigindo formatos de colunas. A etapa mais importante foi a remoção de 224 registros com informações de Churn incompletas para garantir a precisão da nossa análise.
2.  **Análise Exploratória:** Utilizando gráficos de barra e de distribuição, exploramos a relação entre a variável Churn e outras características dos clientes, como tipo de contrato, tempo de serviço e forma de pagamento.

---

#### 📈 **Principais Descobertas**

A análise dos dados revelou padrões muito claros sobre a evasão de clientes. Os gráficos mostraram que a decisão de sair da empresa não é aleatória e está diretamente ligada a fatores específicos:

| Fator de Risco | Perfil do Cliente propenso a Churn |
| :--- | :--- |
| **Tempo de Contrato** | Clientes com **pouco tempo de serviço** (média de **18 meses**) são os que mais saem. |
| **Tipo de Plano** | Clientes com **contratos mensais** têm uma probabilidade muito maior de cancelar o serviço. |
| **Método de Pagamento** | O uso de **cheques eletrônicos** está fortemente associado a uma maior taxa de evasão. |
| **Senioridade** | A taxa de Churn é um pouco mais alta entre clientes idosos. |

---

#### 💡 **Conclusão:** O Perfil do Cliente em Risco

Com base nos dados, podemos traçar o perfil do cliente que tem maior probabilidade de churn: é um cliente **novo**, que optou por um **plano mensal** e que realiza pagamentos via **cheque eletrônico**. Este perfil sugere uma baixa lealdade e um compromisso frágil com a empresa.

---

#### ✅ **Recomendações Estratégicas**

Para reter esses clientes de alto risco e reduzir a taxa de Churn, a TelecomX deve considerar as seguintes ações:

1.  **Foco nos Clientes Novos:**
    * Implementar um programa de boas-vindas e acompanhamento nos primeiros meses.
    * Oferecer um atendimento proativo para garantir a satisfação inicial.
2.  **Incentivar Contratos de Longo Prazo:**
    * Criar ofertas especiais e descontos atraentes para que clientes em planos mensais migrem para contratos anuais.
3.  **Melhorar a Experiência de Pagamento:**
    * Investigar a causa da insatisfação dos clientes que usam cheques eletrônicos.
    * Melhorar a usabilidade e a segurança desse método ou, alternativamente, incentivar a migração para outras formas de pagamento mais estáveis.

Essas recomendações, baseadas em evidências dos dados, podem ajudar a TelecomX a construir relacionamentos mais duradouros e lucrativos com seus clientes.
"""

